server:
  port: 8085

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://mysql:3306/gym_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  liquibase:
    enabled: false
  flyway:
    enabled: false

jwt:
  secret-key: esta_es_mi_compleja_clave_secreta_de_32_caracteres_minimo

springdoc:
  api-docs:
    enabled: true
    path: /auth/v3/api-docs
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

logging:
  level:
    com.grupito.auth_service: INFO
  pattern:
    console: "%d{HH:mm:ss} %-5level %msg%n"