server:
  port: 9095
spring:
  application:
    name: pagos-services
  datasource:
    url: jdbc:mysql://gym-mysql:3306/db_pagos?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
  liquibase:
    enabled: false
urls:
  usuarios-service: http://usuarios-services:9091/usuarios
  reservas-service: http://reservas-services:9093/reservas
springdoc:
  api-docs:
    enabled: true
    path: /pagos/v3/api-docs
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
logging:
  level:
    com.grupito.pagos_services: INFO
  file:
    name: logs/pagos-services.log
  pattern:
    console: "%d{HH:mm:ss} %-5level %msg%n"
    file: "%d{HH:mm:ss} %-5level %msg%n"