services:
  mysql:
    image: mysql:8.0
    container_name: gym-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gym
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  usuarios-service:
    build: ./usuarios-services
    container_name: gym-usuarios
    ports:
      - "9091:9091"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      # - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/gym?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      # - SPRING_DATASOURCE_USERNAME=root
      # - SPRING_DATASOURCE_PASSWORD=root

  rutinas-service:
    build: ./rutinas-services
    container_name: gym-rutinas
    ports:
      - "9092:9092"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      # - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/gym?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      # - SPRING_DATASOURCE_USERNAME=root
      # - SPRING_DATASOURCE_PASSWORD=root

  reservas-service:
    build: ./reservas-services
    container_name: gym-reservas
    ports:
      - "9093:9093"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      # - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/gym?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      # - SPRING_DATASOURCE_USERNAME=root
      # - SPRING_DATASOURCE_PASSWORD=root

  seguimientos-service:
    build: ./seguimientos-services
    container_name: gym-seguimientos
    ports:
      - "9094:9094"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      # - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/gym?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      # - SPRING_DATASOURCE_USERNAME=root
      # - SPRING_DATASOURCE_PASSWORD=root
      - USUARIOS_SERVICE_URL=http://usuarios-service:9091

  pagos-service:
    build: ./pagos-services
    container_name: gym-pagos
    ports:
      - "9095:9095"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      # - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/gym?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      # - SPRING_DATASOURCE_USERNAME=root
      # - SPRING_DATASOURCE_PASSWORD=root
      - USUARIOS_SERVICE_URL=http://usuarios-service:9091
      - RESERVAS_SERVICE_URL=http://reservas-service:9093

  inventario-service:
    build: ./inventario-services
    container_name: gym-inventario
    ports:
      - "9096:9096"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      # - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/gym?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      # - SPRING_DATASOURCE_USERNAME=root
      # - SPRING_DATASOURCE_PASSWORD=root

  recomendaciones-service:
    build: ./recomendaciones-services
    container_name: gym-recomendaciones
    ports:
      - "9097:9097"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      # - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/gym?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      # - SPRING_DATASOURCE_USERNAME=root
      # - SPRING_DATASOURCE_PASSWORD=root

  soporte-service:
    build: ./soporte-services
    container_name: gym-soporte
    ports:
      - "9098:9098"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      # - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/gym?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      # - SPRING_DATASOURCE_USERNAME=root
      # - SPRING_DATASOURCE_PASSWORD=root

  reviews-service:
    build: ./review-services
    container_name: gym-reviews
    ports:
      - "9099:9099"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      # - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/gym?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      # - SPRING_DATASOURCE_USERNAME=root
      # - SPRING_DATASOURCE_PASSWORD=root

  auth-service:
    build: ./auth-service
    container_name: gym-auth
    ports:
      - "8085:8085"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      # - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/gym?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      # - SPRING_DATASOURCE_USERNAME=root
      # - SPRING_DATASOURCE_PASSWORD=root

  api-gateway:
    build: ./api-gateway
    container_name: gym-gateway
    ports:
      - "9090:9090"
    depends_on:
      - auth-service
      - recomendaciones-service
      # - usuarios-service
      # - rutinas-service
      # - reservas-service
      # - seguimientos-service
      # - pagos-service
      # - inventario-service
      # - soporte-service
      # - reviews-service

volumes:
  db-data: