server:
  port: 9097

spring:
  application:
    name: recomendaciones-services
  datasource:
    url: jdbc:mysql://localhost:3306/db_recomendaciones?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: ""
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog.sql

# CONFIGURACIÓN CLAVE PARA EL JWT
jwt:
  secret-key: esta_es_mi_compleja_clave_secreta_de_32_caracteres_minimo

springdoc:
  api-docs:
    enabled: true
    path: /recomendaciones/v3/api-docs
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

logging:
  level:
    com.grupito: INFO
  file:
    name: logs/recomendaciones-services.log
  pattern:
    console: "%d{HH:mm:ss} %-5level %msg%n"
    file: "%d{HH:mm:ss} %-5level %msg%n"