server:
  port: 9090

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: esta_es_mi_compleja_clave_secreta_de_32_caracteres_minimo
  cloud:
    gateway:
      routes:
        # Servicios iniciales
        - id: usuarios-route
          uri: http://usuarios-service:9091
          predicates:
            - Path=/api/usuarios/**
          filters:
            - StripPrefix=1
        - id: rutinas-route
          uri: http://rutinas-service:9092
          predicates:
            - Path=/api/rutinas/**
          filters:
            - StripPrefix=1
        - id: reservas-route
          uri: http://reservas-service:9093
          predicates:
            - Path=/api/reservas/**
          filters:
            - StripPrefix=1
        - id: seguimientos-route
          uri: http://seguimientos-service:9094
          predicates:
            - Path=/api/seguimientos/**
          filters:
            - StripPrefix=1
        - id: pagos-route
          uri: http://pagos-service:9095
          predicates:
            - Path=/api/pagos/**
          filters:
            - StripPrefix=1
<<<<<<< HEAD
        - id: inventario-route
          uri: http://inventario-service:9096
          predicates:
            - Path=/api/inventario/**
          filters:
            - StripPrefix=1
        # Servicios finales
        - id: recomendaciones-route
          uri: http://recomendaciones-service:9097
          predicates:
            - Path=/api/recomendaciones/**
          filters:
            - StripPrefix=1
        - id: soporte-route
          uri: http://soporte-service:9098
          predicates:
            - Path=/api/soporte/**
          filters:
            - StripPrefix=1
        - id: reviews-route
          uri: http://reviews-service:9099
          predicates:
            - Path=/api/reviews/**
          filters:
            - StripPrefix=1
        - id: auth-route
          uri: http://auth-service:8085
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
=======

        - id: inventario-service
          uri: http://localhost:9096
          predicates:
            - Path=/inventario/**

        - id: recomendaciones-service
          uri: http://localhost:9097
          predicates:
            - Path=/recomendaciones/**

        - id: soporte-service
          uri: http://localhost:9098
          predicates:
            - Path=/soporte/**

        - id: review-service
          uri: http://localhost:9099
          predicates:
            - Path=/reviews/**

springdoc:
  swagger-ui:
  
    enabled: true
    urls:
      - name: "Modulo 01: Autenticacion (Auth)"
        url: /auth/v3/api-docs
      - name: "Modulo 02: Gestion de Usuarios"
        url: /usuarios/v3/api-docs
      - name: "Modulo 03: Rutinas de Ejercicio"
        url: /rutinas/v3/api-docs
      - name: "Modulo 04: Reserva de Clases"
        url: /reservas/v3/api-docs
      - name: "Modulo 05: Seguimiento Fisico (Peso/Grasa)"
        url: /seguimientos/v3/api-docs
      - name: "Modulo 06: Pagos y Mensualidades"
        url: /pagos/v3/api-docs
      - name: "Modulo 07: Inventario del Gym"
        url: /inventario/v3/api-docs
      - name: "Modulo 08: Recomendaciones Inteligentes"
        url: /recomendaciones/v3/api-docs
      - name: "Modulo 09: Soporte Tecnico (Tickets)"
        url: /soporte/v3/api-docs
      - name: "Modulo 10: Resenas y Reviews"
        url: /reviews/v3/api-docs
>>>>>>> 74d79a67ff6d62b15b8c0b4edb59eec32e8a60e0
