spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: usuarios-route
          uri: http://localhost:9091
          predicates:
            - Path=/api/usuarios/**
          filters:
            - StripPrefix=1

        - id: rutinas-route
          uri: http://localhost:9092
          predicates:
            - Path=/api/rutinas/**
          filters:
            - StripPrefix=1

        - id: reservas-route
          uri: http://localhost:9093
          predicates:
            - Path=/api/reservas/**
          filters:
            - StripPrefix=1

        - id: seguimientos-route
          uri: http://localhost:9094
          predicates:
            - Path=/api/seguimientos/**
          filters:
            - StripPrefix=1

        - id: pagos-route
          uri: http://localhost:9095
          predicates:
            - Path=/api/pagos/**
          filters:
            - StripPrefix=1

server:
  port: 9090