spring.application.name=rutinas-services

server.port=9092

spring.datasource.url=jdbc:mysql://localhost:3306/db_rutinas?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog.sql

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# OPCIONAL
spring.jpa.open-in-view=false