server:
  port: 9096
<<<<<<< HEAD

spring:
  application:
    name: inventario-service
  datasource:
    # Esta es la URL correcta para Docker (usando 'mysql' en lugar de 'localhost')
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/gym?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka}
=======
spring:
  application:
    name: inventario-services
  datasource:
    url: jdbc:mysql://localhost:3306/db_inventario?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: ""
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog.sql

springdoc:
  api-docs:
    enabled: true
    path: /inventario/v3/api-docs
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
logging:
  level:
    com.grupito: INFO
  file:
    name: logs/inventario-services.log
  pattern:
    console: "%d{HH:mm:ss} %-5level %msg%n"
    file: "%d{HH:mm:ss} %-5level %msg%n"
>>>>>>> 74d79a67ff6d62b15b8c0b4edb59eec32e8a60e0
