spring.application.name=usuarios-services
server.port=9091

spring.datasource.url=jdbc:mysql://localhost:3306/db_usuarios?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog.sql

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

logging.level.com.grupito.usuarios_services=INFO
logging.file.name=logs/usuarios-services.log
springdoc.api-docs.path=/usuarios/v3/api-docs
spring.liquibase.database-changelog-table=LOG_USUARIOS_CHANGELOG
spring.liquibase.database-changelog-lock-table=LOG_USUARIOS_CHANGELOGLOCK