server:
  port: 9099
spring:
  application:
    name: review-services
  datasource:
    url: jdbc:mysql://localhost:3306/db_reviews?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: ""
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog.sql

springdoc:
  api-docs:
    enabled: true
    path: /reviews/v3/api-docs
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
logging:
  level:
    com.grupito: INFO
  file:
    name: logs/review-services.log
  pattern:
    console: "%d{HH:mm:ss} %-5level %msg%n"
    file: "%d{HH:mm:ss} %-5level %msg%n"